all: metal_pipe_falling_sound_effect

run: metal_pipe_falling_sound_effect
	./metal_pipe_falling_sound_effect

metal_pipe_falling_sound_effect:
	g++ -o metal_pipe_falling_sound_effect -std=c++20 -O3 ./*.c++ ./protocol/*.c++ ./pieces/*.c++ ./debug/*.c++

clean:
	rm ./metal_pipe_falling_sound_effect